name: CD/CI Workflow

on: [push, pull_request]

jobs:
  check:
    name: Check

    runs-on: ubuntu-20.04
    env:
      REPORT_GAS: "1"

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Storage layout
        run: npm run storageLayout

      - name: Report LCOV
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: zgosalvez/github-actions-report-lcov@v1.5.0
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 100
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release Package
    runs-on: ubuntu-20.04

    needs: [check]

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"

      - name: Install NPM dependencies
        run: npm ci

      - name: Prepare package
        run: npm run package

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
